algoritmo "Média"
// Função : Algoritmo que solicita dois números para o usuário e calcula a média entre eles.
// Autor :  Tatiana Moreno
// Data : 17/07/2020
// Seção de Declarações
var

numero1, numero2, soma: real

inicio
// Seção de Comandos
   Escreva("Digite o primeiro número: ")
   Leia(numero1)
   Escreva("Digite o segundo número: ")
   Leia(numero2)
   soma <- numero1 + numero2
   Escreva("O total é: ", soma)
fimalgoritmo
